import { Book } from "@/utils/types/books";
import { STATUS_BOOK, TYPE_BOOK } from "@/utils/enums";

export const books: Book[] = [
  {
    id: '1',
    title: 'Para Entender o Caibalion',
    subtitle: 'A Vivência da Filosofia Hermética e sua Prática nos Dias de Hoje',
    author: 'Lúcia Helena Galvão',
    cover: 'https://m.media-amazon.com/images/I/81MwN7Sb+hL._SL1500_.jpg',
    status: STATUS_BOOK.READING,
    rating: 5,
    link: 'https://a.co/d/9Uvm1ku',
    type: TYPE_BOOK.FISICO,
    readIn: 2025
  },
  {
    id: '2',
    title: 'Clean Code',
    subtitle: 'Habilidades Práticas do Agile Software',
    author: 'Robert C. Martin',
    cover: 'https://m.media-amazon.com/images/I/41jEbK-jG+L.jpg',
    status: STATUS_BOOK.READ,
    rating: 5,
    link: 'https://a.co/d/dg0MeUA',
    type: TYPE_BOOK.FISICO,
    readIn: 2020
  },
  {
    id: '3',
    title: 'Arquitetura Limpa',
    subtitle: 'O Guia do Artesão Para Estrutura e Design de Software',
    author: 'Robert C. Martin',
    cover: 'https://m.media-amazon.com/images/I/815d9tE7jSL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    rating: 4,
    link: 'https://a.co/d/dlwn5SP',
    type: TYPE_BOOK.FISICO,
    readIn: 2020
  },
  {
    id: '4',
    title: 'Torto arado',
    author: 'Itamar Vieira Junior',
    cover: 'https://m.media-amazon.com/images/I/71gXpS2PAgL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    rating: 5,
    link: 'https://a.co/d/6YKAXZe',
    type: TYPE_BOOK.FISICO,
    readIn: 2025
  },
  {
    id: '5',
    title: 'A cabeça do santo',
    author: 'Socorro Acioli',
    cover: 'https://m.media-amazon.com/images/I/71-YhujYUxS._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    rating: 5,
    link: 'https://a.co/d/0Esn52u',
    type: TYPE_BOOK.FISICO,
    readIn: 2025
  },
  {
    id: '6',
    title: 'Nascido para correr',
    subtitle: 'A experiência de descobrir uma nova vida',
    author: 'Christopher McDougall',
    cover: 'https://m.media-amazon.com/images/I/71-l6r9UAkL._SL1500_.jpg',
    status: STATUS_BOOK.READING,
    link: 'https://a.co/d/2LdIP7p',
    rating: 5,
    type: TYPE_BOOK.KINDLE,
  },
  {
    id: '7',
    title: 'Descolonizando afetos',
    subtitle: 'Experimentações sobre outras formas de amar',
    author: 'Geni Núñez',
    cover: 'https://m.media-amazon.com/images/I/71+URF9TeiL._SL1500_.jpg',
    status: STATUS_BOOK.READING,
    rating: 3,
    link: 'https://a.co/d/a8lDK8s',
    type: TYPE_BOOK.FISICO
  },
  {
    id: '8',
    title: 'Os Exilados da Capela',
    author: 'Edgard Armond',
    cover: 'https://m.media-amazon.com/images/I/71I-5cC6oaL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/52iY1n5',
    rating: 4,
    type: TYPE_BOOK.FISICO,
    readIn: 2025
  },
  {
    id: '9',
    title: 'Umbanda para iniciantes',
    author: 'Rodrigo Queiroz',
    cover: 'https://m.media-amazon.com/images/I/71h29PYqECL._SL1360_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/0Rto53K',
    rating: 5,
    type: TYPE_BOOK.FISICO,
    readIn: 2025
  },
  {
    id: '10',
    title: 'Sapiens',
    subtitle: 'Uma breve história da humanidade',
    author: 'Yuval Noah Harari',
    cover: 'https://m.media-amazon.com/images/I/71-ghLb8qML._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/dCk3VmX',
    rating: 5,
    readIn: 2023,
    type: TYPE_BOOK.KINDLE
  },
  {
    id: '11',
    title: 'Hábitos Atômicos',
    subtitle: 'Um Método Fácil e Comprovado de Criar Bons Hábitos e se Livrar dos Maus',
    author: 'James Clear',
    cover: 'https://m.media-amazon.com/images/I/81eT2pjx4jL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/dBhfiPq',
    rating: 5,
    readIn: 2023,
    type: TYPE_BOOK.KINDLE
  },
  {
    id: '12',
    title: 'A acusação',
    subtitle: 'Histórias proibidas vindas da Coreia do Norte',
    author: 'Vários Autores',
    cover: 'https://m.media-amazon.com/images/I/81Zb5YuQWxS._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/7o89s1r',
    rating: 5,
    type: TYPE_BOOK.FISICO,
    readIn: 2023
  },
  {
    id: '13',
    title: 'Mãos de luz',
    subtitle: 'Um Guia Para a Cura Através do Campo de Energia Humano ',
    author: 'Barbara Ann Brennan',
    cover: 'https://m.media-amazon.com/images/I/81yW1Gqi2ZL._SL1500_.jpg',
    status: STATUS_BOOK.READING,
    link: 'https://a.co/d/afjqYwh',
    rating: 5,
    type: TYPE_BOOK.FISICO,
  },
  {
    id: '14',
    title: 'Sob o céu de Aruanda',
    author: 'Filipi Brasil',
    cover: 'https://m.media-amazon.com/images/I/9158AbyFlVS._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/6Y9Z9j6',
    rating: 5,
    type: TYPE_BOOK.KINDLE,
    readIn: 2024
  },
  {
    id: '15',
    title: 'Corpo fechado',
    author: 'Médium: Robson Pinheiro / Ditado por: W. Voltz / Orientado por: Ângelo Inácio',
    cover: 'https://m.media-amazon.com/images/I/8164LHIfJCL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/buwTUR2',
    rating: 5,
    type: TYPE_BOOK.KINDLE,
    readIn: 2024
  },
  {
    id: '16',
    title: 'Tambores de Angola',
    author: 'Robson Pinheiro',
    cover: 'https://m.media-amazon.com/images/I/71roS7f3GyL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/fmIAyH1',
    rating: 5,
    type: TYPE_BOOK.KINDLE,
    readIn: 2024
  },

  {
    id: '17',
    title: 'As 5 linguagens do amor',
    subtitle: 'Como expressar um compromisso de amor a seu cônjuge',
    author: 'Gary Chapman',
    cover: 'https://m.media-amazon.com/images/I/81K7XEw5ZvL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/0kPUYjS',
    rating: 4,
    type: TYPE_BOOK.KINDLE,
    readIn: 2023
  },
  {
    id: '18',
    title: 'A quietude é a chave',
    author: 'Ryan Holiday',
    cover: 'https://m.media-amazon.com/images/I/712kvxCRs4L._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/6H5CX99',
    rating: 5,
    type: TYPE_BOOK.KINDLE,
    readIn: 2023
  },
  {
    id: '19',
    title: 'Acolhendo sua criança interior',
    subtitle: 'Uma abordagem inovadora para curar as feridas da infância',
    author: 'Stefanie Stahl',
    cover: 'https://m.media-amazon.com/images/I/81fyJqqSEIL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/6zkSs4M',
    rating: 5,
    type: TYPE_BOOK.KINDLE,
    readIn: 2023
  },
  {
    id: '20',
    title: 'Do que eu falo quando falo de corrida',
    author: 'Haruki Murakami',
    cover: 'https://m.media-amazon.com/images/I/81aPAmQRmZL._SL1500_.jpg',
    status: STATUS_BOOK.READ,
    link: 'https://a.co/d/d3A6yy8',
    rating: 5,
    type: TYPE_BOOK.KINDLE,
    readIn: 2023
  },
];