name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0,0 * * *' # every 00:00
jobs:
  build:
    name: twobanks
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5ffa7fa72b73fc5a06916c34
