name: Trigger Netlify Build
on:
  schedule:
    - cron: '* */3 * * *' # every 3 hours
jobs:
  build:
    name: twostrava
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5fceb83faaceab4633ea5f46
