export { default as Footer} from './Footer'
export { default as Header} from './Header'
export { default as Strava} from './Strava'
export { default as NowPlaying} from './NowPlaying'
export { default as Banks} from './Banks'
export { default as Title} from './Title'
export { default as Icon } from './Icon'
